python ASTARTraslados.py ./ASTAR-tests/locations01.csv 1
python ASTARTraslados.py ./ASTAR-tests/locations01.csv 2
python ASTARTraslados.py ./ASTAR-tests/locations01.csv 3
python ASTARTraslados.py ./ASTAR-tests/locations01.csv 4
python ASTARTraslados.py ./ASTAR-tests/locations02.csv 1
python ASTARTraslados.py ./ASTAR-tests/locations02.csv 2
python ASTARTraslados.py ./ASTAR-tests/locations02.csv 3
python ASTARTraslados.py ./ASTAR-tests/locations02.csv 4
python ASTARTraslados.py ./ASTAR-tests/locations03.csv 1
python ASTARTraslados.py ./ASTAR-tests/locations03.csv 2
python ASTARTraslados.py ./ASTAR-tests/locations03.csv 3
python ASTARTraslados.py ./ASTAR-tests/locations03.csv 4
python ASTARTraslados.py ./ASTAR-tests/locations04.csv 1
python ASTARTraslados.py ./ASTAR-tests/locations04.csv 2
python ASTARTraslados.py ./ASTAR-tests/locations04.csv 3
python ASTARTraslados.py ./ASTAR-tests/locations04.csv 4
python ASTARTraslados.py ./ASTAR-tests/locations05.csv 1
python ASTARTraslados.py ./ASTAR-tests/locations05.csv 2
python ASTARTraslados.py ./ASTAR-tests/locations05.csv 3
python ASTARTraslados.py ./ASTAR-tests/locations05.csv 4
python ASTARTraslados.py ./ASTAR-tests/locations06.csv 1
python ASTARTraslados.py ./ASTAR-tests/locations06.csv 2
python ASTARTraslados.py ./ASTAR-tests/locations06.csv 3
python ASTARTraslados.py ./ASTAR-tests/locations06.csv 4
python ASTARTraslados.py ./ASTAR-tests/locations07.csv 1
python ASTARTraslados.py ./ASTAR-tests/locations07.csv 2
python ASTARTraslados.py ./ASTAR-tests/locations07.csv 3
python ASTARTraslados.py ./ASTAR-tests/locations07.csv 4
